Branch: main; commit-msg: Realizado tratamento para permitir informar APENAS números no id da tarefa "#[0-9]+".

diff --git a/policies/default/commit-msg b/policies/default/commit-msg
--- a/policies/default/commit-msg
+++ b/policies/default/commit-msg
@@ -38,11 +38,11 @@ MESSAGE_INFO="info: "
 MESSAGE_HELP_SCM="Em caso de duvidas, entre em contato com a equipe de GCS."
 
 # RegEx
-# REGEX_TASK_ID_MESSAGE="#[0-9]+[ ][-][ ]+[a-zA-Z].{15,}+$"
-# REGEX_TASK_ID_MESSAGE="#[0-9]+[ ][-][ ]+[a-zA-z0-9].{15,}.+$"
-REGEX_TASK_ID_MESSAGE="[;][ ]+#[0-9]+[ ][-][ ]+[a-zA-z0-9].{15,}.+$"
+REGEX_TASK_ID_MESSAGE="[;][ ]+#[0-9]+[ ][-][ ]+[a-zA-Z0-9].{15,}.+$"
 REGEX_PREFIX_BRANCH="^$BRANCH_PREFIX[ ][a-zA-Z0-9]{2}"
-REGEX_TASK_ID="#[0-9]+"
+REGEX_TASK_ID="; #[a-zA-Z0-9]+ - "
+REGEX_TASK_ID_ONLY_NUMBERS="#[0-9]+"
+REGEX_ONLY_NUMBERS="^[0-9]+$"
 REGEX_BUGFIX_BRANCH="^bugfix-[0-9]+$"
 REGEX_FEATURE_BRANCH="^feature-[0-9]+$"
 REGEX_TRAINING_BRANCH="^training-[0-9]+$"
@@ -224,7 +224,7 @@ echo ""
 
 if ! [[ "$commitMessage" =~ $REGEX_PREFIX_BRANCH ]]; then
 	if [ -n "$taskIdBranchName" ] && [ "$isEpicBranch" == false ]; then
-		if ! [[ "$commitMessage" =~ "#$taskIdBranchName" ]] && ! [[ "$commitMessage" =~ $REGEX_TASK_ID ]]; then
+		if ! [[ "$commitMessage" =~ "#$taskIdBranchName" ]] && ! [[ "$commitMessage" =~ $REGEX_TASK_ID_ONLY_NUMBERS ]]; then
 			echo "#$taskIdBranchName"" - $commitMessage" > "$1"
 			echo "$tagHookName $MESSAGE_INFO"
 			setCommitMessage "$1"
@@ -257,17 +257,25 @@ if ! [[ "$commitMessage" =~ ^"${prefixCurrentBranch}" ]]; then
 	exit 1
 fi
 
-# echo "$commitMessage [$repositoryName]" > "$1"
-# setCommitMessage "$1"
-# echo "$tagHookName $MESSAGE_INFO"
-# echo "Adicionado o nome do repositorio no final da mensagem do commit: '[$repositoryName]'"
-# echo "Mensagem atualizada:"
-# echo "$commitMessage"
-# echo ""
+if [[ "$commitMessage" =~ $REGEX_TASK_ID ]]; then
+	echo "$tagHookName $MESSAGE_INFO"
+	echo "Verificando se o id da tarefa informado na mensagem do commit contem apenas numeros"
+	echo ""
+
+	taskIdCommitMessage="$(echo $commitMessage | cut -d '#' -f 2 | cut -d '-' -f 1 | sed 's/ //g')"
+
+	if ! [[ "$taskIdCommitMessage" =~ $REGEX_ONLY_NUMBERS ]]; then
+		echo "$tagHookName $MESSAGE_ERROR"
+		echo "O id da tarefa informado na mensagem do commit deve conter apenas numeros: #$taskIdCommitMessage!"
+		echo "Mensagem do commit:"
+		echo "$commitMessage"
+		exit 1
+	fi
+else
+	taskIdCommitMessage=""
+fi
 
 if ! ( [ "$userSCM" == true ] && [[ "$commitMessage" =~ "$(echo LS1uby12ZXJpZnktcG9saWNpZXMtaG9vawo= | "$pathBase64" -d)" ]] ); then
-	taskId="$(echo $commitMessage | cut -d '#' -f 2 | cut -d '-' -f 1 | sed "s/ //g")"
-
 	if ! [[ "$commitMessage" =~ "$(echo LS1uby12ZXJpZnktbWVzc2FnZS1wYXR0ZXJuCg== | "$pathBase64" -d)" ]]; then
 		if ! [[ "$commitMessage" =~ "$(echo LS1uby12ZXJpZnktdGFzay1pZC1jb21taXQtbWVzc2FnZS1tYXRjaGVzLWJyYW5jaC1uYW1lCg== | "$pathBase64" -d)" ]]; then
 			if [ -n "$taskIdBranchName" ] && [ "$isEpicBranch" == false ]; then
